"""add chunks table and update course fields

Revision ID: 6f9acb0371cc
Revises: 354fd9a293a1
Create Date: 2026-08-22 23:05:34.767152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6f9acb0371cc'
down_revision: Union[str, Sequence[str], None] = '354fd9a293a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.add_column('courses', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('num_pages', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'word_count')
    op.drop_column('courses', 'num_pages')
    op.drop_column('courses', 'filename')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
